name: build

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  android:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level:
          - 23
        java-version:
          - 11

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.5.0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.6

      - name: Configure JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: gradle

      - name: Build the Plugin
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: clean ktlintCheck build -s
          
      - name: Run Unit Tests
        run: rm -rf ~/.m2/repository/com/jaredsburrows/gradle-spoon-plugin/ && ./gradlew publishToMavenLocal -x test -s

      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          api-level: ${{ matrix.api-level }}
          script: cd test-app && ../gradlew clean spoonDebugAndroidTest checkReports -s && cd ..
        env:
          API_LEVEL: ${{ matrix.api-level }}

      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action/composite@v2.6.1
        if: success() || failure()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        if: github.repository == 'jaredsburrows/gradle-spoon-plugin' && github.ref == 'refs/heads/master'
        with:
          name: gradle-spoon-plugin-${{ github.workflow }}-${{ github.run_id }}
          path: |
            build/libs
            build/outputs
            build/publications
            build/distributions
            build/reports
            build/test-results
          if-no-files-found: warn

  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'jaredsburrows/gradle-spoon-plugin' && github.ref == 'refs/heads/master'
    needs:
      - android

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.5.0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.6

      - name: Configure JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Publish
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: publish -s
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
