name: build

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  android:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        api-level:
          - 23
        java-version:
          - 11

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Configure JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Build the Plugin
        run: ./gradlew clean ktlintCheck build -s

      - name: Run Unit Tests
        run: rm -rf ~/.m2/repository/com/jaredsburrows/gradle-spoon-plugin/ && ./gradlew publishToMavenLocal -x test -s

      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: cd test-app && ../gradlew clean spoonDebugAndroidTest checkReports -s && cd ..
        env:
          API_LEVEL: ${{ matrix.api-level }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.0
        if: always()
        with:
          name: gradle-spoon-plugin-${{ github.workflow }}-${{ github.run_id }}
          path: |
            build/libs
            build/outputs
            build/publications
            build/distributions
            build/reports
            build/test-results
          if-no-files-found: warn

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - android

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Configure JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: temurin
          java-version: 11

      - name: Publish
        run: ./gradlew clean publish -s
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
